[pytest]
DJANGO_SETTINGS_MODULE = CBT_psy.settings
python_files = tests.py test_*.py *_tests.py
addopts = --no-migrations  --create-db
testpaths =
    appointment_app/tests/
    psyproducts_app/tests/
    payments_app/tests/
    integration_tests/
    bot/tests/

asyncio_mode = auto