# Generated by Django 5.2.5 on 2025-08-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный продукт')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Для бесплатных продуктов оставить 0', max_digits=10, verbose_name='Цена')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='products/documents/', verbose_name='Файл методички')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
    ]
