# Generated by Django 5.2.5 on 2025-09-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('consultation_type', models.CharField(choices=[('first', 'Первичная консультация (90 мин)'), ('follow', 'Повторная консультация (60 мин)')], max_length=10, verbose_name='Тип консультации')),
                ('date', models.DateField(verbose_name='Дата консультации')),
                ('time', models.TimeField(verbose_name='Время консультации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Запись на консультацию',
                'verbose_name_plural': 'Записи на консультации',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Доступная дата')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
            ],
            options={
                'verbose_name': 'Доступная дата',
                'verbose_name_plural': 'Доступные даты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NewDatesSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='Chat ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Подписчик на новые даты',
                'verbose_name_plural': 'Подписчики на новые даты',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Telegram уведомление',
                'verbose_name_plural': 'Telegram уведомления',
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Доступное время')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда забронировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='appointment_app.availabledate')),
            ],
            options={
                'verbose_name': 'Доступное время',
                'verbose_name_plural': 'Доступное время',
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
