# Generated by Django 5.2.5 on 2025-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pd_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД получено'),
        ),
    ]
