# Generated by Django 5.2.5 on 2025-08-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя Telegram')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первого взаимодействия')),
                ('subscribed_to_newsletter', models.BooleanField(default=False, verbose_name='Подписан на рассылку')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название материала')),
                ('content_type', models.CharField(choices=[('gift_guide', 'Бесплатный гайд (лид-магнит)'), ('checklist', 'Чек-лист'), ('memo', 'Памятка'), ('about_method', 'О методе КПТ'), ('about_consultation', 'О консультациях')], max_length=20, verbose_name='Тип контента')),
                ('description', models.TextField(verbose_name='Описание (для админки)')),
                ('file', models.FileField(blank=True, null=True, upload_to='content/%Y/%m/%d/', verbose_name='Файл')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст контента')),
                ('telegram_command_trigger', models.CharField(blank=True, max_length=50, null=True, verbose_name='Команда в боте для вызова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_issue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основная проблема')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('contacted', 'Связались'), ('completed', 'Консультация состоялась'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='bot.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запрос на консультацию',
                'verbose_name_plural': 'Запросы на консультацию',
            },
        ),
    ]
