# Generated by Django 5.2.5 on 2025-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content_type', models.CharField(choices=[('article', 'Статья'), ('tip', 'Совет'), ('exercise', 'Упражнение'), ('video', 'Видео'), ('audio', 'Аудио')], max_length=20, verbose_name='Тип материала')),
                ('content', models.FileField(blank=True, null=True, upload_to='newsletter/%Y/%m/%d/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Материал рассылки',
                'verbose_name_plural': 'Материалы рассылки',
            },
        ),
    ]
