# Generated by Django 5.2.5 on 2025-09-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_newslettermaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDatesSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подписка активна')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dates_subscription', to='bot.client')),
            ],
            options={
                'verbose_name': 'Подписка на новые даты',
                'verbose_name_plural': 'Подписки на новые даты',
            },
        ),
    ]
