# Generated by Django 5.2.5 on 2025-08-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='Год/Период')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Год обучения',
                'verbose_name_plural': 'Годы обучения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExcludeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название направления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Исключенное направление',
                'verbose_name_plural': 'Исключенные направления',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainAppIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='ServiceQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название запроса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Запрос для работы',
                'verbose_name_plural': 'Запросы для работы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main_app.education')),
            ],
            options={
                'verbose_name': 'Достижение/Сертификат',
                'verbose_name_plural': 'Достижения/Сертификаты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiplomaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diplomas/', verbose_name='Изображение диплома')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_images', to='main_app.educationachievement')),
            ],
            options={
                'verbose_name': 'Изображение диплома',
                'verbose_name_plural': 'Изображения дипломов',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('achievement', 'order'), name='unique_diploma_image_order')],
            },
        ),
    ]
