"""
Django settings for CBT_psy project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import tempfile
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET')  # Случайная строка для безопасности
WEBHOOK_URL = os.getenv('WEBHOOK_URL')  # Или туннель URL для разработки
CONSULTATION_PAGE_URL = os.getenv('CONSULTATION_PAGE_URL')
BOOKING_URL = os.getenv('BOOKING_URL')  # бронирование времени и даты
WORK_STAGES_URL = os.getenv('WORK_STAGES_URL')  #  Этапы работы
CONSULTATION_RULES_URL = os.getenv('CONSULTATION_RULES_URL')  # Правила консультаций


# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.yandex.ru')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'alenaemilevna@yandex.ru')



PAYMENT_CARD_ATTEMPTS_LIMIT = 3  # Лимит попыток ввода карты
PAYMENT_TIMEOUT_MINUTES = 30      # Таймаут платежа




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://sitdipsy.ru",
    "https://www.sitdipsy.ru",
    "http://159.194.196.36",
]

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_app',
    'psyproducts_app',
    'corsheaders',
    'bot',
    'appointment_app',
    'moms_channel_app',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CBT_psy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CBT_psy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Используется драйвер postgresql
        'NAME': os.getenv('POSTGRES_DB'),  # Название БД
        'USER': os.getenv('POSTGRES_USER'),  # Имя пользователя БД
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),  # Пароль пользователя
        'HOST': os.getenv('POSTGRES_HOST'),  # Адрес сервера (Локально или удаленно)
        'PORT': os.getenv('POSTGRES_PORT') or '5432',  # Порт подключения
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Настройки Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Yekaterinburg'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

# Режим тестирования (False по умолчанию)
TESTING = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Путь URL, по которому браузер будет запрашивать статические файлы
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]  # Директории, откуда django собирает статику.
STATIC_ROOT = os.getenv('STATIC_ROOT')  # Папка куда будут собраны статичные файлы командой collectstatic


MEDIA_URL = '/media/'  # Базовый URL для загрузки медиа-контента(изображения, документы и т.д.)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Физический путь директории, где сохраняются загруженные пользователями файлы
TEST_MEDIA_ROOT = os.path.join(BASE_DIR, 'test_media')  # Отдельная папка для сохранения медиафайлов в тестовых средах


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для тестовых медиафайлов
if 'test' in sys.argv:
    # Используем временную папку для медиафайлов в тестах
    MEDIA_ROOT = tempfile.mkdtemp()

    # Настройка тестовой БД
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'test_' + os.getenv('POSTGRES_DB', 'cbt_psy'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'TEST': {
                'NAME': 'test_' + os.getenv('POSTGRES_DB', 'cbt_psy'),
            }
        }
    }

    # Ускорение тестов паролей
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]

    # Отключаем Celery в тестах
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

    #TBANK_WEBHOOK_SECRET = os.getenv('TBANK_WEBHOOK_SECRET', 'test_webhook_secret_for_tests')